#! /bin/bash

#
# MIT License
# 
# Copyright (c) 2020 Yuta Hirokawa
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

devicelist=/tmp/$$.devicelist
networksetup -listallnetworkservices > ${devicelist}
sed -i -e "1d" ${devicelist}

ENABLED_DEVICE="none"
PRE_IFS=$IFS
IFS=$'\n'
for dev in `cat ${devicelist}`
do
  ipaddr=`networksetup -getinfo $dev | grep "^IP address"`
  if [ $? -eq 0 ]; then
    ENABLED_DEVICE="$dev"
    break
  fi
done
IFS=$PRE_IFS
rm ${devicelist}

if [ "$ENABLED_DEVICE" != "none" ]; then
  echo $ENABLED_DEVICE
  exit 0
else
  exit 1
fi
